namespace: konaai-dev  # Change to "default" if you're moving everything there
deployment:
  name: konaai-dev-ui
replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/konaai-dev-462909/konaai-gke/dev-ui
  tag: latest
  pullPolicy: IfNotPresent
container:
  name: ui-container
  port: 80
service:
  name: ui-service
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    memory: "128Mi"
    cpu: "70m"
  limits:
    memory: "128Mi"
    cpu: "300m"
labels:
  app: ui-app
autoscaling:
  enabled: true       # set true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
serviceAccount:
  create: false
ingress:
  enabled: true
  name: konaai-dev-ingress
  className: nginx
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    
  hosts:
    - host: konaai-sit.mykonaai.com
      paths:
  hosts:
    - host: konaai-sit.mykonaai.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: ui-service
          servicePort: 80

    - host: konaai-api.mykonaai.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: api-service
          servicePort: 80
  tls:
    - hosts:
        - konaai-sit.mykonaai.com
        - konaai-api.mykonaai.com
      secretName: godaddy-wildcard

config:
  name: konaai-dev-config
  apiBaseUrl: "https://test-api.mykonaai.com/api"
  ODataUrl: "https://test-api.mykonaai.com/v1"
  reportUrl: "https://test-api.mykonaai.com/api/report"
  authUrl: "https://test-api.mykonaai.com/api/auth"
  Datamanager: "https://test-api.mykonaai.com/"
      
