apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  app-config.json: |
    {
      "apiBaseUrl": "{{ .Values.config.apiBaseUrl }}",
      "ODataUrl": "{{ .Values.config.ODataUrl }}",
      "reportUrl": "{{ .Values.config.reportUrl }}",
      "authUrl": "{{ .Values.config.authUrl }}",
      "Datamanager": "{{ .Values.config.Datamanager }}"
    }
